const routes = {
  HOME: "/home",
  SIGNIN: process.env.PUBLIC_URL + "/signin",
  CHOOSEACCOUNT: process.env.PUBLIC_URL + "/chooseAccount",
  SIGNUP: process.env.PUBLIC_URL + "/signup",
  VERIFYEMAIL: process.env.PUBLIC_URL + "/verifyEmail",
  WELCOME: process.env.PUBLIC_URL + "/welcome",
  FORGOTPWD: process.env.PUBLIC_URL + "/forgotpassword",
  DASHBOARD: process.env.PUBLIC_URL + "/dashboard",
  VIEWERDASHBOARD: process.env.PUBLIC_URL + "/viewerDashboard",
  EDITPROFILE: process.env.PUBLIC_URL + "/editprofile",
  EDITUSER: process.env.PUBLIC_URL + "/edituser",
  ADDEVENT: process.env.PUBLIC_URL + "/addevent",
  MYEVENT: process.env.PUBLIC_URL + "/myevents",
  EDITEVENT: process.env.PUBLIC_URL + "/editevent",
  LIVEEVENT: process.env.PUBLIC_URL + "/liveevent",
  UPCOMINGEVENTS: process.env.PUBLIC_URL + "/upcomingevents",
  MAKEPAYMENT: process.env.PUBLIC_URL + "/makepayment",
  // PAYMENTMETHOD: process.env.PUBLIC_URL + "/paymentmethod",
  PAYMENT: process.env.PUBLIC_URL + "/payment",
  WALLET: process.env.PUBLIC_URL + "/wallet",
  TRANSACTION: process.env.PUBLIC_URL + "/transaction",

  MEETING: process.env.PUBLIC_URL + "/meeting",
  RESETPWD: process.env.PUBLIC_URL + "/resetPassword",
  PRIVACYPOLICY: process.env.PUBLIC_URL + "/privacyPolicy",
  TERMSANDCONDITIONS: process.env.PUBLIC_URL + "/termsAndCondition",

  SESSION: process.env.PUBLIC_URL + "/session",
  STREAM: process.env.PUBLIC_URL + "/stream",

  OFFER: process.env.PUBLIC_URL + "/offer",
  VIEWERPROFILE: process.env.PUBLIC_URL + "/viewerprofile",
  VIEWEREVENT: process.env.PUBLIC_URL + "/viewerevent",
  VIEWEREVENTWITHOUTLOGIN: process.env.PUBLIC_URL + "/viewereventwlogin",
  SUBSCRIPTIONPURCHASE: process.env.PUBLIC_URL + "/subscribe",
  SUBSCRIBELIST: process.env.PUBLIC_URL + "/subscribelist",
  ADDSUBSCRIPTION: process.env.PUBLIC_URL + "/addsubscription",
  MYSUBSCRIPTION: process.env.PUBLIC_URL + "/mysubscription",
  // MAKEPAYMENT: process.env.PUBLIC_URL + "/makepayment",
  // SUBSCRIBE: "/subscribe",
  // OFFER: "/offer",
};

export default routes;
